from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

class Ui_AddStockWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #8b7bff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #Enrty Expied
        self.expiryObatDateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.expiryObatDateEdit.setGeometry(QtCore.QRect(410, 210, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.expiryObatDateEdit.setFont(font)
        self.expiryObatDateEdit.setStyleSheet("color: #000000; background-color: #eeeeee; selection-color: #8b7bff;")
        self.expiryObatDateEdit.setObjectName("expiryObatDateEdit")
        self.expiryObatDateEdit.setCalendarPopup(True)
        #Combobox Stock
        self.stockSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.stockSpinBox.setGeometry(QtCore.QRect(410, 310, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.stockSpinBox.setFont(font)
        self.stockSpinBox.setStyleSheet("color: #000000; background-color: #eeeeee;")
        self.stockSpinBox.setObjectName("stockSpinBox")
        #Combobx Tye obat
        self.typeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.typeComboBox.setGeometry(QtCore.QRect(410, 410, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.typeComboBox.setFont(font)
        self.typeComboBox.setStyleSheet("color: #000000; background-color: #eeeeee;")
        self.typeComboBox.addItems(["Obat Bebas", "Obat Bebas Terbatas", "Obat Keras"])
        self.typeComboBox.setObjectName("typeComboBox")
        #Enrty Obat
        self.namaObatField = QtWidgets.QLineEdit(self.centralwidget)
        self.namaObatField.setGeometry(QtCore.QRect(410, 110, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.namaObatField.setFont(font)
        self.namaObatField.setStyleSheet("color: #000000; background-color: #eeeeee;")
        self.namaObatField.setObjectName("namaObatField")
        self.namaObatLabel = QtWidgets.QLabel(self.centralwidget)
        self.namaObatLabel.setGeometry(QtCore.QRect(100, 110, 161, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.namaObatLabel.setFont(font)
        self.namaObatLabel.setStyleSheet("color: #000000;")
        self.namaObatLabel.setObjectName("namaObatLabel")
        #label expied
        self.tanggalObatLabel = QtWidgets.QLabel(self.centralwidget)
        self.tanggalObatLabel.setGeometry(QtCore.QRect(100, 210, 251, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.tanggalObatLabel.setFont(font)
        self.tanggalObatLabel.setStyleSheet("color: #000000;")
        self.tanggalObatLabel.setObjectName("tanggalObatLabel")
        #label stock
        self.stokObatLabel = QtWidgets.QLabel(self.centralwidget)
        self.stokObatLabel.setGeometry(QtCore.QRect(100, 310, 251, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.stokObatLabel.setFont(font)
        self.stokObatLabel.setStyleSheet("color: #000000;")
        self.stokObatLabel.setObjectName("stokObatLabel")
        #label Type obat
        self.tipeObatLabel = QtWidgets.QLabel(self.centralwidget)
        self.tipeObatLabel.setGeometry(QtCore.QRect(100, 410, 251, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.tipeObatLabel.setFont(font)
        self.tipeObatLabel.setStyleSheet("color: #000000;")
        self.tipeObatLabel.setObjectName("tipeObatLabel")
        #judul 
        self.judulPageLabel = QtWidgets.QLabel(self.centralwidget)
        self.judulPageLabel.setGeometry(QtCore.QRect(170, 20, 471, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        self.judulPageLabel.setFont(font)
        self.judulPageLabel.setStyleSheet("color: #000000;")
        self.judulPageLabel.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)

        self.judulPageLabel.setObjectName("judulPageLabel")
        self.simpanObatButton = QtWidgets.QPushButton(self.centralwidget)
        self.simpanObatButton.setGeometry(QtCore.QRect(320, 480, 300, 40))
        #font simpan button
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.simpanObatButton.setFont(font)
        self.simpanObatButton.setStyleSheet("border: 1px solid #000000; background-color: #fed100; color: #000000; border-radius: 50%; ")
        self.simpanObatButton.setObjectName("simpanObatButton")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(20, 10, 91, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Stock"))
        self.namaObatLabel.setText(_translate("MainWindow", "Nama Obat"))
        self.tanggalObatLabel.setText(_translate("MainWindow", "Tanggal Kadaluarsa Obat"))
        self.stokObatLabel.setText(_translate("MainWindow", "Jumlah Stok Obat"))
        self.tipeObatLabel.setText(_translate("MainWindow", "Tipe / Jenis Obat"))
        self.judulPageLabel.setText(_translate("MainWindow", "Tambah Data Obat Baru"))
        self.simpanObatButton.setText(_translate("MainWindow", "Simpan"))
        self.backButton.setText(_translate("MainWindow", "Back"))
