
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

class Ui_HomeWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("HomeWindow")
        MainWindow.resize(800, 600)
        MainWindow.setFixedSize(800, 600)
        MainWindow.setStyleSheet("")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #bacground Image
        self.bg_frame = QtWidgets.QLabel(self.centralwidget)
        self.bg_frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.bg_frame.setStyleSheet("background-image: url('home_bg.png');")
        self.bg_frame.setText("")
        self.bg_frame.setObjectName("bg_frame")
        #profile icon
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 51, 51))
        self.label_2.setStyleSheet("background-image: url('home_bg.png');")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        #profile icon
        self.profileIcon = QtWidgets.QLabel(self.centralwidget)
        self.profileIcon.setGeometry(QtCore.QRect(40, 30, 41, 41))
        pixmapProfileIcon = QtGui.QPixmap("profile_icon.png")
        self.profileIcon.setPixmap(pixmapProfileIcon)
        self.profileIcon.setScaledContents(True)
        self.profileIcon.setText("")
        self.profileIcon.setObjectName("profileIcon")
        self.addStockIcon = QtWidgets.QLabel(self.centralwidget)
        self.addStockIcon.setGeometry(QtCore.QRect(90, 340, 120, 120))
        pixmapAddStockIcon = QtGui.QPixmap("add_stock_icon.png")
        self.addStockIcon.setPixmap(pixmapAddStockIcon)
        self.addStockIcon.setScaledContents(True)
        self.addStockIcon.setStyleSheet("border: 5px solid #4466b9;")
        self.addStockIcon.setObjectName("addStockIcon")
        self.viewStockButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewStockButton.setGeometry(QtCore.QRect(260, 340, 120, 120))
        pixmapViewStockIcon = QtGui.QIcon(QtGui.QPixmap("view_stock_icon.png"))
        self.viewStockButton.setIcon(pixmapViewStockIcon)
        self.viewStockButton.setStyleSheet("border: 5px solid #4466b9;")
        self.viewStockButton.setObjectName("viewStockIcon")
        self.viewStockButton.setIconSize(self.viewStockButton.size() - QtCore.QSize(5, 5))
    
        self.expiryButton = QtWidgets.QPushButton(self.centralwidget)
        self.expiryButton.setGeometry(QtCore.QRect(430, 340, 120, 120))
        pixmapExpiryIcon = QtGui.QIcon(QtGui.QPixmap("expiry_icon.png"))
        self.expiryButton.setIcon(pixmapExpiryIcon)
        self.expiryButton.setStyleSheet("border: 5px solid #4466b9;")
        self.expiryButton.setObjectName("expiryIcon")
        self.expiryButton.setIconSize(self.expiryButton.size() - QtCore.QSize(5, 5))
     
        self.lowStockButton = QtWidgets.QPushButton(self.centralwidget)
        self.lowStockButton.setGeometry(QtCore.QRect(600, 340, 120, 120))
        pixmapLowStockIcon = QtGui.QIcon(QtGui.QPixmap("low_icon.png"))
        self.lowStockButton.setIcon(pixmapLowStockIcon)
        self.lowStockButton.setStyleSheet("border: 5px solid #4466b9;")
        self.lowStockButton.setObjectName("lowStockIcon")
        self.lowStockButton.setIconSize(self.lowStockButton.size() - QtCore.QSize(5, 5))
    
        self.addStockLabel = QtWidgets.QLabel(self.centralwidget)
        self.addStockLabel.setGeometry(QtCore.QRect(90, 470, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        self.addStockLabel.setFont(font)
        self.addStockLabel.setStyleSheet("color: #000000;")
        self.addStockLabel.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.addStockLabel.setObjectName("addStockLabel")
        self.viewStockLabel = QtWidgets.QLabel(self.centralwidget)
        self.viewStockLabel.setGeometry(QtCore.QRect(260, 470, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        self.viewStockLabel.setFont(font)
        self.viewStockLabel.setStyleSheet("color: #000000;")
        self.viewStockLabel.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.viewStockLabel.setObjectName("viewStockLabel")
        self.expiryLabel = QtWidgets.QLabel(self.centralwidget)
        self.expiryLabel.setGeometry(QtCore.QRect(430, 470, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        self.expiryLabel.setFont(font)
        self.expiryLabel.setStyleSheet("color: #000000;")
        self.expiryLabel.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.expiryLabel.setObjectName("expiryLabel")
        self.lowLabel = QtWidgets.QLabel(self.centralwidget)
        self.lowLabel.setGeometry(QtCore.QRect(590, 470, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        self.lowLabel.setFont(font)
        self.lowLabel.setStyleSheet("color: #000000;")
        self.lowLabel.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.lowLabel.setObjectName("lowLabel")
        #app label
        self.appNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.appNameLabel.setGeometry(QtCore.QRect(100, 10, 210, 90))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        self.appNameLabel.setFont(font)
        self.appNameLabel.setStyleSheet("color: #000000;")
        self.appNameLabel.setObjectName("appNameLabel")
        #Medicine Report
        self.medicineReportLabel = QtWidgets.QLabel(self.centralwidget)
        self.medicineReportLabel.setGeometry(QtCore.QRect(470, 30, 225, 45))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(True)
        self.medicineReportLabel.setFont(font)
        self.medicineReportLabel.setStyleSheet("color: #bc8741;")
        self.medicineReportLabel.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.medicineReportLabel.setObjectName("medicineReportLabel")
        #Title Label Managemnt Stock Report
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(150, 110, 491, 131))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(25)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: #000000;")
        self.titleLabel.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.titleLabel.setObjectName("titleLabel")
        #Deskripsi Add stock
        self.addStockDescriptionLabel = QtWidgets.QLabel(self.centralwidget)
        self.addStockDescriptionLabel.setGeometry(QtCore.QRect(90, 490, 120, 50))
        font = QtGui.QFont()
        #deskripsi
        font.setFamily("Helvetica")
        self.addStockDescriptionLabel.setFont(font)
        self.addStockDescriptionLabel.setStyleSheet("color: #000000;")
        self.addStockDescriptionLabel.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.addStockDescriptionLabel.setObjectName("addStockDescriptionLabel")
        self.viewStockDescriptionLabel = QtWidgets.QLabel(self.centralwidget)
        self.viewStockDescriptionLabel.setGeometry(QtCore.QRect(260, 490, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.viewStockDescriptionLabel.setFont(font)
        self.viewStockDescriptionLabel.setStyleSheet("color: #000000;")
        self.viewStockDescriptionLabel.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.viewStockDescriptionLabel.setObjectName("viewStockDescriptionLabel")
        self.expiryDescriptionLabel = QtWidgets.QLabel(self.centralwidget)
        self.expiryDescriptionLabel.setGeometry(QtCore.QRect(430, 490, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.expiryDescriptionLabel.setFont(font)
        self.expiryDescriptionLabel.setStyleSheet("color: #000000;")
        self.expiryDescriptionLabel.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.expiryDescriptionLabel.setObjectName("expiryDescriptionLabel")
        self.lowDescriptionLabel = QtWidgets.QLabel(self.centralwidget)
        self.lowDescriptionLabel.setGeometry(QtCore.QRect(600, 490, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.lowDescriptionLabel.setFont(font)
        self.lowDescriptionLabel.setStyleSheet("color: #000000;")
        self.lowDescriptionLabel.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.lowDescriptionLabel.setObjectName("lowDescriptionLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Home Page"))
        self.addStockLabel.setText(_translate("MainWindow", "Add Stock"))
        self.viewStockLabel.setText(_translate("MainWindow", "View Stock"))
        self.expiryLabel.setText(_translate("MainWindow", "Expiry Alert"))
        self.lowLabel.setText(_translate("MainWindow", "Low Stock Alert"))
        self.appNameLabel.setText(_translate("MainWindow", "Pharmacy Inventory <br> Management System"))
        self.medicineReportLabel.setText(_translate("MainWindow", "Medicine Report"))
        self.titleLabel.setText(_translate("MainWindow", "Management Stock <br> Report"))
        self.addStockDescriptionLabel.setText(_translate("MainWindow", "Enter Medicine <br> Details Here"))
        self.viewStockDescriptionLabel.setText(_translate("MainWindow", "See or Update <br> Products List"))
        self.expiryDescriptionLabel.setText(_translate("MainWindow", "Monitor <br> Expiring Products"))
        self.lowDescriptionLabel.setText(_translate("MainWindow", "List of Low Stock <br> Products"))
    